/*
 * Firefly III API
 *
 * This is the official documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. This version of the API is live from version v4.7.9 and onwards. You may use the \"Authorize\" button to try the API below. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutocompleteAccount {
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the account found by an auto-complete search.
    #[serde(rename = "name")]
    pub name: String,
    /// Asset accounts and liabilities have a second field with the given date's account balance.
    #[serde(rename = "name_with_balance")]
    pub name_with_balance: String,
    /// Account type of the account found by the auto-complete search.
    #[serde(rename = "type")]
    pub _type: String,
    /// Currency ID for this account.
    #[serde(rename = "currency_id")]
    pub currency_id: i32,
    /// Currency code for this account.
    #[serde(rename = "currency_code")]
    pub currency_code: String,
    #[serde(rename = "currency_symbol")]
    pub currency_symbol: String,
    #[serde(rename = "currency_decimal_places")]
    pub currency_decimal_places: i32,
}

impl AutocompleteAccount {
    pub fn new(id: String, name: String, name_with_balance: String, _type: String, currency_id: i32, currency_code: String, currency_symbol: String, currency_decimal_places: i32) -> AutocompleteAccount {
        AutocompleteAccount {
            id,
            name,
            name_with_balance,
            _type,
            currency_id,
            currency_code,
            currency_symbol,
            currency_decimal_places,
        }
    }
}


