/*
 * Firefly III API
 *
 * This is the official documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. This version of the API is live from version v4.7.9 and onwards. You may use the \"Authorize\" button to try the API below. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutocompleteCurrency {
    #[serde(rename = "id")]
    pub id: String,
    /// Currency name.
    #[serde(rename = "name")]
    pub name: String,
    /// Currency code for this account.
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "decimal_places")]
    pub decimal_places: i32,
}

impl AutocompleteCurrency {
    pub fn new(id: String, name: String, code: String, symbol: String, decimal_places: i32) -> AutocompleteCurrency {
        AutocompleteCurrency {
            id,
            name,
            code,
            symbol,
            decimal_places,
        }
    }
}


