/*
 * Firefly III API
 *
 * This is the official documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. This version of the API is live from version v4.7.9 and onwards. You may use the \"Authorize\" button to try the API below. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutocompleteBudget {
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the budget found by an auto-complete search.
    #[serde(rename = "name")]
    pub name: String,
}

impl AutocompleteBudget {
    pub fn new(id: String, name: String) -> AutocompleteBudget {
        AutocompleteBudget {
            id,
            name,
        }
    }
}


