/*
 * Firefly III API
 *
 * This is the official documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. This version of the API is live from version v4.7.9 and onwards. You may use the \"Authorize\" button to try the API below. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutocompletePiggyBalance {
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the piggy bank found by an auto-complete search.
    #[serde(rename = "name")]
    pub name: String,
    /// Name of the piggy bank found by an auto-complete search with the current balance formatted nicely.
    #[serde(rename = "name_with_balance", skip_serializing_if = "Option::is_none")]
    pub name_with_balance: Option<String>,
    /// Currency ID for this piggy bank.
    #[serde(rename = "currency_id", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<i32>,
    /// Currency code for this piggy bank.
    #[serde(rename = "currency_code", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<String>,
    #[serde(rename = "currency_symbol", skip_serializing_if = "Option::is_none")]
    pub currency_symbol: Option<String>,
    #[serde(rename = "currency_decimal_places", skip_serializing_if = "Option::is_none")]
    pub currency_decimal_places: Option<i32>,
}

impl AutocompletePiggyBalance {
    pub fn new(id: String, name: String) -> AutocompletePiggyBalance {
        AutocompletePiggyBalance {
            id,
            name,
            name_with_balance: None,
            currency_id: None,
            currency_code: None,
            currency_symbol: None,
            currency_decimal_places: None,
        }
    }
}


